version: '3'
services:
  verdaccio:
      container_name: "verdaccio-${CONTAINER_NAME}"
      build:
          dockerfile: Dockerfile
      ports:
          - "4873:4873"
      volumes:
          - "./storage:/verdaccio/storage"
          - "./conf:/verdaccio/conf"
          - "./logs:/verdaccio/logs"
