#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/packages/config/src/conf
#

# path to a directory with all packages
storage: /verdaccio/storage

auth:
    github-oauth-ui:
        client-id: GITHUB_CLIENT_ID
        client-secret: GITHUB_CLIENT_SECRET
        token: GITHUB_TOKEN

security:
    api:
        jwt:
            sign:
                expiresIn: 60d
                notBefore: 1
    web:
        sign:
            expiresIn: 7d

packages:

middlewares:
    audit:
        enabled: true
    github-oauth-ui:
        enabled: true

web:
    enable: true
    title: TITLE
    logo: /verdaccio/public/logo.png
    favicon: /verdaccio/public/favicon.ico
    login: true
    darkMode: true
    rateLimit:
        windowMs: 50000
        max: 1000

# log settings
logs:
    - { type: stdout, format: pretty, level: trace }
    - { type: file, path: /verdaccio/logs/verdaccio.log, level: info }
